wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.27.2
    framework: huggingface
    huggingface_version: 5.13.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1784237526
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 71
      - 98
      3:
      - 4
      - 7
      - 13
      - 16
      - 19
      - 42
      - 62
      - 66
      4: 3.11.5
      5: 0.27.2
      6: 5.13.1
      9:
        1: transformers_trainer
      13: linux-x86_64
    e:
      jo0aftl1dlp4tea1clh73jhh4to23jyn:
        os: Linux-5.14.0-570.44.1.el9_6.x86_64-x86_64-INTEL-R-_XEON-R-_PLATINUM_8570-with-glibc2.37
        python: CPython 3.11.5
        started_at: '2026-07-16T21:32:05.630569Z'
        program: /home/lerdman/Curiosity-by-Design/Code/supplementary-material/clarification_module.py
        code_path: Code/supplementary-material/clarification_module.py
        code_path_local: Code/supplementary-material/clarification_module.py
        git:
          remote_url: https://github.com/lerdman183/Curiosity-by-Design.git
          commit: 139217ae4ecab6e16b47600442de9de9a6f5ae08
        root: /home/lerdman/Curiosity-by-Design
        host: g4.nibi.sharcnet
        executable: /local/scratch/lerdman.17801343.0/ENV/bin/python
        cpu_count: 112
        cpu_count_logical: 112
        gpu_type: NVIDIA H100 80GB HBM3
        gpu_count: 1
        disk:
          /:
            total: '432833581056'
            used: '79646720'
        memory:
          total: '2164167892992'
        gpu_nvidia:
        - name: NVIDIA H100 80GB HBM3
          memory_total: '85520809984'
          cuda_cores: 16896
          architecture: Hopper
          uuid: GPU-18023060-6070-1e11-ac9a-d6f12db891b8
        cuda_version: '13.0'
        slurm:
          job_end_time: '1784280695'
          cluster_name: nibi
          cpu_bind_type: 'mask_cpu:'
          tres_per_task: cpu=1
          job_name: clarify-gemma
          job_account: def-lutellie_gpu
          job_user: lerdman
          step_nodelist: g4
          tasks_per_node: '1'
          localid: '0'
          procid: '0'
          task_pid: '2911559'
          step_id: '0'
          job_uid: '3160427'
          job_id: '17801343'
          topology_addr: top.gswitch.g4
          step_gpus: '1'
          topology_addr_pattern: switch.switch.node
          job_gid: '3160427'
          job_gpus: '1'
          launch_node_ipaddr: 10.37.162.4
          mem_per_node: '18000'
          job_cpus_per_node: '1'
          distribution: block
          stepid: '0'
          step_num_nodes: '1'
          step_launcher_port: '60963'
          gpus_on_node: '1'
          cpu_bind_verbose: quiet
          gtids: '0'
          cpus_on_node: '1'
          step_tasks_per_node: '1'
          mpi_type: pmix
          job_nodelist: g4
          tmpdir: /local/scratch/lerdman.17801343.0
          job_qos: normal
          nnodes: '1'
          conf: /etc/slurm/slurm.conf
          job_num_nodes: '1'
          oom_kill_step: '0'
          cpus_per_task: '1'
          umask: '0027'
          jobid: '17801343'
          pmix_mapping_serv: (vector,(0,1,1))
          srun_comm_host: 10.37.162.4
          submit_host: l1.nibi.sharcnet
          script_context: prolog_task
          nodeid: '0'
          cpu_bind_list: '0x0000000000000000000000000100'
          nprocs: '1'
          ntasks: '1'
          job_start_time: '1784237495'
          restart_count: '0'
          srun_comm_port: '60963'
          submit_dir: /home/lerdman/Curiosity-by-Design
          nodelist: g4
          home: /opt/software/slurm/24.11.7
          job_partition: gpubase_bygpu_b2
          prio_process: '0'
          cpu_bind: quiet,mask_cpu:0x0000000000000000000000000100
          step_num_tasks: '1'
          pmixp_abort_agent_port: '60962'
        writer_id: jo0aftl1dlp4tea1clh73jhh4to23jyn
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
model:
  desc: null
  value: google/gemma-3-1b-it
dataset:
  desc: null
  value: /home/lerdman/Curiosity-by-Design/Code/supplementary-material/../../Datasets/clarification_module_synth_dataset.json
epochs:
  desc: null
  value: 3
seq_len:
  desc: null
  value: 512
batch_per_device:
  desc: null
  value: 1
grad_accum:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 5.0e-05
peft_config:
  desc: null
  value:
    default:
      task_type: CAUSAL_LM
      peft_type: LORA
      auto_mapping: null
      peft_version: 0.19.1
      base_model_name_or_path: google/gemma-3-1b-it
      revision: null
      inference_mode: false
      r: 8
      target_modules:
      - q_proj
      - k_proj
      exclude_modules: null
      lora_alpha: 32
      lora_dropout: 0.1
      fan_in_fan_out: false
      bias: none
      use_rslora: false
      modules_to_save: null
      init_lora_weights: true
      layers_to_transform: null
      layers_pattern: null
      rank_pattern: {}
      alpha_pattern: {}
      megatron_config: null
      megatron_core: megatron.core
      trainable_token_indices: null
      loftq_config: {}
      eva_config: null
      corda_config: null
      lora_ga_config: null
      use_dora: false
      alora_invocation_tokens: null
      use_qalora: false
      qalora_group_size: 16
      layer_replication: null
      runtime_config:
        ephemeral_gpu_offload: false
      lora_bias: false
      target_parameters: null
      use_bdlora: null
      arrow_config: null
      ensure_weight_tying: false
transformers_version:
  desc: null
  value: 5.13.1
architectures:
  desc: null
  value:
  - Gemma3ForCausalLM
output_hidden_states:
  desc: null
  value: false
return_dict:
  desc: null
  value: true
dtype:
  desc: null
  value: float16
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
problem_type:
  desc: null
  value: null
vocab_size:
  desc: null
  value: 262144
hidden_size:
  desc: null
  value: 1152
intermediate_size:
  desc: null
  value: 6912
num_hidden_layers:
  desc: null
  value: 26
num_attention_heads:
  desc: null
  value: 4
num_key_value_heads:
  desc: null
  value: 1
head_dim:
  desc: null
  value: 256
hidden_activation:
  desc: null
  value: gelu_pytorch_tanh
max_position_embeddings:
  desc: null
  value: 32768
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-06
use_cache:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value:
  - 1
  - 106
bos_token_id:
  desc: null
  value: 2
tie_word_embeddings:
  desc: null
  value: true
rope_parameters:
  desc: null
  value:
    sliding_attention:
      rope_type: default
      rope_theta: 10000
    full_attention:
      rope_type: default
      rope_theta: 1000000
attention_bias:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
query_pre_attn_scalar:
  desc: null
  value: 256
sliding_window:
  desc: null
  value: 512
layer_types:
  desc: null
  value:
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - full_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - full_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - full_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - sliding_attention
  - full_attention
  - sliding_attention
  - sliding_attention
final_logit_softcapping:
  desc: null
  value: null
attn_logit_softcapping:
  desc: null
  value: null
use_bidirectional_attention:
  desc: null
  value: false
_sliding_window_pattern:
  desc: null
  value: 6
_name_or_path:
  desc: null
  value: google/gemma-3-1b-it
cache_implementation:
  desc: null
  value: hybrid
model_type:
  desc: null
  value: gemma3_text
sliding_window_pattern:
  desc: null
  value: 6
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ./gemma3-1b-it-ft-new-data
per_device_train_batch_size:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 3
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
lr_scheduler_kwargs:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 0
optim:
  desc: null
  value: adamw_torch_fused
optim_args:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
optim_target_modules:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 2
average_tokens_across_devices:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 1.0
label_smoothing_factor:
  desc: null
  value: 0.0
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: true
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value: null
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
use_liger_kernel:
  desc: null
  value: false
liger_kernel_config:
  desc: null
  value: null
neftune_noise_alpha:
  desc: null
  value: null
torch_empty_cache_steps:
  desc: null
  value: null
auto_find_batch_size:
  desc: null
  value: false
logging_strategy:
  desc: null
  value: steps
logging_steps:
  desc: null
  value: 10
logging_first_step:
  desc: null
  value: false
log_on_each_node:
  desc: null
  value: true
logging_nan_inf_filter:
  desc: null
  value: true
include_num_input_tokens_seen:
  desc: null
  value: 'no'
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
disable_tqdm:
  desc: null
  value: false
report_to:
  desc: null
  value:
  - wandb
run_name:
  desc: null
  value: gemma3-1b-it-singleGPU
project:
  desc: null
  value: huggingface
trackio_space_id:
  desc: null
  value: null
trackio_bucket_id:
  desc: null
  value: null
trackio_static_space_id:
  desc: null
  value: null
eval_strategy:
  desc: null
  value: 'no'
eval_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
per_device_eval_batch_size:
  desc: null
  value: 8
prediction_loss_only:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
eval_do_concat_batches:
  desc: null
  value: true
eval_use_gather_object:
  desc: null
  value: false
eval_accumulation_steps:
  desc: null
  value: null
include_for_metrics:
  desc: null
  value: []
batch_eval_metrics:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_on_each_node:
  desc: null
  value: false
save_total_limit:
  desc: null
  value: 3
enable_jit_checkpoint:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_always_push:
  desc: null
  value: false
hub_revision:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
use_cpu:
  desc: null
  value: false
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
parallelism_config:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 1
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
dataloader_prefetch_factor:
  desc: null
  value: null
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
train_sampling_strategy:
  desc: null
  value: random
length_column_name:
  desc: null
  value: length
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_static_graph:
  desc: null
  value: null
ddp_backend:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
fsdp:
  desc: null
  value: null
fsdp_config:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
debug:
  desc: null
  value: []
skip_memory_metrics:
  desc: null
  value: true
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
warmup_ratio:
  desc: null
  value: null
logging_dir:
  desc: null
  value: null
local_rank:
  desc: null
  value: -1
model/num_parameters:
  desc: null
  value: 1000631424
